### ISSUE TITLE
Additional extent functionality for secondary_weights

### ISSUE THREAD

**Issue by gmcdonald-sfg** [tcarleton/stagg#14]
For `secondary_weights`, currently the only extent option is to provide a vector that defines a bounding box. I wonder if instead or in addition to this, you could have an additional argument (e.g., `extent_sf`) that would take as an input an `sf` object, and automatically calculate the extent using the bounding box of the `sf` object.

In the Kansas example you walk through in the read me, the user could then simply input `kansas_counties` into this function to get the appropriate extent, rather than needing to calculate the extent beforehand.

**Comment by saraorofino** [comment]
Hi @gmcdonald-sfg thank you for pointing this out. We looked into it more and realized that other formats are already compatible with `stagg`, like `st_bbox()` and `raster::extent()`. We have updated the README and the function documentation to clarify that any object compatible with `raster::crop()` would work as an input for `extent` argument. Thanks for bringing this to our attention!
