### ISSUE TITLE
Read me documentation: data download

### ISSUE THREAD

**Issue by gmcdonald-sfg** [tcarleton/stagg#15]
When I first read the package description and abstract, I assumed that this package would also handle the downloading of data from ERA5 directly through R. I understand now that this may be outside the scope of what you're trying to achieve here. But it would be good to make that more explicit - this package is for users who have already downloaded the data from the ERA5 website, and the package is all about processing those data.

Is there anything the user needs to know about exactly how they need to download data from ERA5 in order to ensure the `stagg` package can work with those data? For example, do you need to make sure you download the data as a raster or raster brick, and avoid downloading in other formats that you can't handle within `stagg`? Will any pre-processing of the downloaded data be necessary before using `stagg`? Perhaps it could be helpful to add a bit of documentation on this.

**Comment by saraorofino** [comment]
Hi @gmcdonald-sfg thank you for this suggestion! We have talked extensively about adding a data download feature and it's on our list of possible future updates but for now the package doesn't include this. We have added a section the beginning of the README which provides links to a few existing R packages for downloading climate data and a list of requirements of the data to be compatible with `stagg`. This is really helpful and important information so thank you for the suggestion.
