### ISSUE TITLE
Printed statements output from functions

### ISSUE THREAD

**Issue by anna-boser** [tcarleton/stagg#4]
I love love love how the secondary weights function has a bit of a dialogue about what it's doing, especially with the use of the crayon package ;). However, I think it would be good to put some more thought about what exactly we would want these messages to be. What are the steps that are happening behind the scenes? What can we report to make the user understand what's happened to their data better? I haven't yet gone through the other functions, but I can imagine we might want to spend some time thinking about printed statements for the other functions too

**Comment by tliddell4** [comment]
I've added some changes but I feel like this is pretty subjective and tough to pin down what good looks like, so I'll leave this issue open for others to see.
