### ISSUE TITLE
Format of examples when running ?stagg::function

### ISSUE THREAD

**Issue by anna-boser** [tcarleton/stagg#5]
I just tried retrieving information about staggregate_bin and think it looks great, but the example is a bit hard to read and understand relative to what I've seen for other packages. It doesn't show you reading in the data and doesn't show the output (ex head(output) would be nice. Also, going to a new line after specifying each new argument would probably improve readability

**Comment by tliddell4** [comment]
That's a good point, I could just format the examples like in the readme

**Comment by tliddell4** [comment]
I think I took care of everything here, if its still an issue let me know.
